// <auto-generated/>
#nullable enable

using System.Collections.Generic;

namespace MoonBuggy.Core.Plural
{
    /// <summary>
    /// AST nodes for CLDR plural rule conditions.
    /// Grammar: condition = or_condition; or_condition = and_condition ("or" and_condition)*;
    /// and_condition = relation ("and" relation)*; relation = expr ("=" | "!=") range_list
    /// </summary>
    internal sealed class OrExpr
    {
        public List<AndExpr> Branches { get; }

        public OrExpr(List<AndExpr> branches)
        {
            Branches = branches;
        }
    }

    internal sealed class AndExpr
    {
        public List<Relation> Relations { get; }

        public AndExpr(List<Relation> relations)
        {
            Relations = relations;
        }
    }

    internal sealed class Relation
    {
        public string Operand { get; }      // n, i, v, w, f, t, e
        public int? Modulus { get; }         // null if no % operator
        public bool Negated { get; }         // true for !=
        public List<RangeValue> Ranges { get; } // comma-separated values/ranges

        public Relation(string operand, int? modulus, bool negated, List<RangeValue> ranges)
        {
            Operand = operand;
            Modulus = modulus;
            Negated = negated;
            Ranges = ranges;
        }
    }

    internal sealed class RangeValue
    {
        public long Low { get; }
        public long High { get; }  // same as Low for single values

        public RangeValue(long low, long high)
        {
            Low = low;
            High = high;
        }

        public RangeValue(long value) : this(value, value) { }

        public bool IsSingle => Low == High;
        public bool Contains(long value) => value >= Low && value <= High;
    }
}
