// <auto-generated/>
// Generated from CLDR plurals.json — do not edit by hand.
#nullable enable

namespace MoonBuggy.Core.Plural
{
    internal static class CldrPluralRules
    {
        internal static PluralCategory GetCategory(string locale, long n)
        {
            switch (locale)
            {
                case "af":
                case "an":
                case "asa":
                case "ast":
                case "az":
                case "bal":
                case "bem":
                case "bez":
                case "bg":
                case "brx":
                case "ce":
                case "cgg":
                case "chr":
                case "ckb":
                case "da":
                case "de":
                case "dv":
                case "ee":
                case "el":
                case "en":
                case "eo":
                case "et":
                case "eu":
                case "fi":
                case "fo":
                case "fur":
                case "fy":
                case "gl":
                case "gsw":
                case "ha":
                case "haw":
                case "hu":
                case "ia":
                case "ie":
                case "io":
                case "jgo":
                case "jmc":
                case "ka":
                case "kaj":
                case "kcg":
                case "kk":
                case "kkj":
                case "kl":
                case "ks":
                case "ksb":
                case "ku":
                case "ky":
                case "lb":
                case "lg":
                case "lij":
                case "mas":
                case "mgo":
                case "ml":
                case "mn":
                case "mr":
                case "nah":
                case "nb":
                case "nd":
                case "ne":
                case "nl":
                case "nn":
                case "nnh":
                case "no":
                case "nr":
                case "ny":
                case "nyn":
                case "om":
                case "or":
                case "os":
                case "pap":
                case "ps":
                case "rm":
                case "rof":
                case "rwk":
                case "saq":
                case "sc":
                case "sd":
                case "sdh":
                case "seh":
                case "sn":
                case "so":
                case "sq":
                case "ss":
                case "ssy":
                case "st":
                case "sv":
                case "sw":
                case "syr":
                case "ta":
                case "te":
                case "teo":
                case "tig":
                case "tk":
                case "tn":
                case "tr":
                case "ts":
                case "ug":
                case "ur":
                case "uz":
                case "ve":
                case "vo":
                case "vun":
                case "wae":
                case "xh":
                case "xog":
                case "yi":
                    if (n == 1) return PluralCategory.One;
                    return PluralCategory.Other;
                case "ak":
                case "bho":
                case "csw":
                case "guw":
                case "ln":
                case "mg":
                case "nso":
                case "pa":
                case "ti":
                case "wa":
                    if (n >= 0 && n <= 1) return PluralCategory.One;
                    return PluralCategory.Other;
                case "am":
                case "as":
                case "bn":
                case "doi":
                case "fa":
                case "gu":
                case "hi":
                case "kn":
                case "kok":
                case "kok-Latn":
                case "pcm":
                case "zu":
                    if (n == 0 || n == 1) return PluralCategory.One;
                    return PluralCategory.Other;
                case "ar":
                case "ars":
                    if (n == 0) return PluralCategory.Zero;
                    if (n == 1) return PluralCategory.One;
                    if (n == 2) return PluralCategory.Two;
                    if (n % 100 >= 3 && n % 100 <= 10) return PluralCategory.Few;
                    if (n % 100 >= 11 && n % 100 <= 99) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "be":
                case "ru":
                case "uk":
                    if (n % 10 == 1 && n % 100 != 11) return PluralCategory.One;
                    if (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) return PluralCategory.Few;
                    if (n % 10 == 0 || n % 10 >= 5 && n % 10 <= 9 || n % 100 >= 11 && n % 100 <= 14) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "blo":
                case "cv":
                case "ksh":
                    if (n == 0) return PluralCategory.Zero;
                    if (n == 1) return PluralCategory.One;
                    return PluralCategory.Other;
                case "bm":
                case "bo":
                case "dz":
                case "hnj":
                case "id":
                case "ig":
                case "ii":
                case "ja":
                case "jbo":
                case "jv":
                case "jw":
                case "kde":
                case "kea":
                case "km":
                case "ko":
                case "lkt":
                case "lo":
                case "ms":
                case "my":
                case "nqo":
                case "osa":
                case "sah":
                case "ses":
                case "sg":
                case "su":
                case "th":
                case "to":
                case "tpi":
                case "und":
                case "vi":
                case "wo":
                case "yo":
                case "yue":
                case "zh":
                    return PluralCategory.Other;
                case "br":
                    if (n % 10 == 1 && (n % 100 != 11 && n % 100 != 71 && n % 100 != 91)) return PluralCategory.One;
                    if (n % 10 == 2 && (n % 100 != 12 && n % 100 != 72 && n % 100 != 92)) return PluralCategory.Two;
                    if (((n % 10 >= 3 && n % 10 <= 4) || n % 10 == 9) && ((n % 100 < 10 || n % 100 > 19) && (n % 100 < 70 || n % 100 > 79) && (n % 100 < 90 || n % 100 > 99))) return PluralCategory.Few;
                    if (n != 0 && n % 1000000 == 0) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "bs":
                case "hr":
                case "sh":
                case "sr":
                    if (n % 10 == 1 && n % 100 != 11) return PluralCategory.One;
                    if (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) return PluralCategory.Few;
                    return PluralCategory.Other;
                case "ca":
                case "es":
                case "it":
                case "lld":
                case "pt-PT":
                case "scn":
                case "vec":
                    if (n == 1) return PluralCategory.One;
                    if (n != 0 && n % 1000000 == 0) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "ceb":
                case "fil":
                case "tl":
                    if ((n == 1 || n == 2 || n == 3) || (n % 10 != 4 && n % 10 != 6 && n % 10 != 9)) return PluralCategory.One;
                    return PluralCategory.Other;
                case "cs":
                case "sk":
                    if (n == 1) return PluralCategory.One;
                    if (n >= 2 && n <= 4) return PluralCategory.Few;
                    return PluralCategory.Other;
                case "cy":
                    if (n == 0) return PluralCategory.Zero;
                    if (n == 1) return PluralCategory.One;
                    if (n == 2) return PluralCategory.Two;
                    if (n == 3) return PluralCategory.Few;
                    if (n == 6) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "dsb":
                case "hsb":
                case "sl":
                    if (n % 100 == 1) return PluralCategory.One;
                    if (n % 100 == 2) return PluralCategory.Two;
                    if (n % 100 >= 3 && n % 100 <= 4) return PluralCategory.Few;
                    return PluralCategory.Other;
                case "ff":
                case "hy":
                case "kab":
                case "si":
                    if ((n == 0 || n == 1)) return PluralCategory.One;
                    return PluralCategory.Other;
                case "fr":
                    if ((n == 0 || n == 1)) return PluralCategory.One;
                    if (n != 0 && n % 1000000 == 0) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "ga":
                    if (n == 1) return PluralCategory.One;
                    if (n == 2) return PluralCategory.Two;
                    if (n >= 3 && n <= 6) return PluralCategory.Few;
                    if (n >= 7 && n <= 10) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "gd":
                    if ((n == 1 || n == 11)) return PluralCategory.One;
                    if ((n == 2 || n == 12)) return PluralCategory.Two;
                    if (((n >= 3 && n <= 10) || (n >= 13 && n <= 19))) return PluralCategory.Few;
                    return PluralCategory.Other;
                case "gv":
                    if (n % 10 == 1) return PluralCategory.One;
                    if (n % 10 == 2) return PluralCategory.Two;
                    if ((n % 100 == 0 || n % 100 == 20 || n % 100 == 40 || n % 100 == 60 || n % 100 == 80)) return PluralCategory.Few;
                    return PluralCategory.Other;
                case "he":
                case "iu":
                case "naq":
                case "sat":
                case "se":
                case "sma":
                case "smi":
                case "smj":
                case "smn":
                case "sms":
                    if (n == 1) return PluralCategory.One;
                    if (n == 2) return PluralCategory.Two;
                    return PluralCategory.Other;
                case "is":
                case "mk":
                    if (n % 10 == 1 && n % 100 != 11) return PluralCategory.One;
                    return PluralCategory.Other;
                case "kw":
                    if (n == 0) return PluralCategory.Zero;
                    if (n == 1) return PluralCategory.One;
                    if ((n % 100 == 2 || n % 100 == 22 || n % 100 == 42 || n % 100 == 62 || n % 100 == 82) || (n % 1000 == 0 && ((n % 100000 >= 1000 && n % 100000 <= 20000) || n % 100000 == 40000 || n % 100000 == 60000 || n % 100000 == 80000)) || (n != 0 && n % 1000000 == 100000)) return PluralCategory.Two;
                    if ((n % 100 == 3 || n % 100 == 23 || n % 100 == 43 || n % 100 == 63 || n % 100 == 83)) return PluralCategory.Few;
                    if (n != 1 && (n % 100 == 1 || n % 100 == 21 || n % 100 == 41 || n % 100 == 61 || n % 100 == 81)) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "lag":
                    if (n == 0) return PluralCategory.Zero;
                    if ((n == 0 || n == 1) && n != 0) return PluralCategory.One;
                    return PluralCategory.Other;
                case "lt":
                    if (n % 10 == 1 && (n % 100 < 11 || n % 100 > 19)) return PluralCategory.One;
                    if (n % 10 >= 2 && n % 10 <= 9 && (n % 100 < 11 || n % 100 > 19)) return PluralCategory.Few;
                    return PluralCategory.Other;
                case "lv":
                case "prg":
                    if (n % 10 == 0 || n % 100 >= 11 && n % 100 <= 19) return PluralCategory.Zero;
                    if (n % 10 == 1 && n % 100 != 11) return PluralCategory.One;
                    return PluralCategory.Other;
                case "mo":
                case "ro":
                    if (n == 1) return PluralCategory.One;
                    if (n == 0 || (n != 1 && n % 100 >= 1 && n % 100 <= 19)) return PluralCategory.Few;
                    return PluralCategory.Other;
                case "mt":
                    if (n == 1) return PluralCategory.One;
                    if (n == 2) return PluralCategory.Two;
                    if (n == 0 || n % 100 >= 3 && n % 100 <= 10) return PluralCategory.Few;
                    if (n % 100 >= 11 && n % 100 <= 19) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "pl":
                    if (n == 1) return PluralCategory.One;
                    if (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) return PluralCategory.Few;
                    if ((n != 1 && n % 10 >= 0 && n % 10 <= 1) || n % 10 >= 5 && n % 10 <= 9 || n % 100 >= 12 && n % 100 <= 14) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "pt":
                    if (n >= 0 && n <= 1) return PluralCategory.One;
                    if (n != 0 && n % 1000000 == 0) return PluralCategory.Many;
                    return PluralCategory.Other;
                case "sgs":
                    if (n % 10 == 1 && n % 100 != 11) return PluralCategory.One;
                    if (n == 2) return PluralCategory.Two;
                    if (n != 2 && n % 10 >= 2 && n % 10 <= 9 && (n % 100 < 11 || n % 100 > 19)) return PluralCategory.Few;
                    return PluralCategory.Other;
                case "shi":
                    if (n == 0 || n == 1) return PluralCategory.One;
                    if (n >= 2 && n <= 10) return PluralCategory.Few;
                    return PluralCategory.Other;
                case "tzm":
                    if (n >= 0 && n <= 1 || n >= 11 && n <= 99) return PluralCategory.One;
                    return PluralCategory.Other;
                default:
                    if (n == 1) return PluralCategory.One;
                    return PluralCategory.Other;
            }
        }
    }
}
